### ISSUE TITLE
锵锵锵，我又来反馈bug了 ...(｡•ˇ‸ˇ•｡) ...

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/MoegirlViewer#6]
总共有以下这么几个问题😜
1.点击图片无法跳转到详细页，出现白屏
2.带有链接的词语重定向到一些特殊界面（如带模板前缀的）无法显示
3.分享链接在h萌娘数据源里时分享的依旧是萌娘百科的链接
4.动态主题显示黑色时标题颜色应变成白色
5.切换到黑夜模式后按钮应变成切换回白天模式
实际都是一些小bug了，顺便说一下我要开学了，高考之前可能不再会与你联系，h萌娘有不少有意思的界面，离开父母之后没事你可以去那里玩玩[拜拜]

**Comment by koharubiyori** [comment]
下版本解决，顺祝学业顺利！
