### ISSUE TITLE
一些<s>炫酷</s>的建议

### ISSUE THREAD

**Issue by 850710247liu** [koharubiyori/MoegirlViewer#7]
1.图标可以换了!!! h萌娘上的萌字已被我重新设计，现在这里直接访问图片
https://www.hmoegirl.com/images/2/29/大H萌字.png
2.可以增加一个和首页一样颜色的主题（<s>大概是绅士黄？？？</s>）
3.条目的二级标题前面可以增加一个加粗的竖线（最好跟随主题颜色），便于和内容分割开
4.希望能增加上传图片功能 QAQ
5.h萌上有一些是用繁体中文书写的最好增加一个简体转换

**Comment by koharubiyori** [comment]
1. 登录界面的图标可以换这个，应用图标个人认为还是绿字比较好。切换数据源是作为一个附加功能存在的，应该以萌百为主。
1. 这个可以有。
1. 之前的版本是有竖线的，后来取消了。原因是加上后某种程度上增强了是在看网页的poi(感觉)，我希望尽可能消除“我在使用一个内嵌了萌百网页的应用”这样的感觉。
1. 暂不考虑。目前的定位是“提供简单且便捷的编辑功能”（加两句话，改几个错字），毕竟编辑的人不多，用mv编辑的就更少。未来可能会添加完整的编辑功能，像是代码高亮，上传图片，查看编辑历史，撤销编辑，查看差异等等。当前的主要目标是把浏览效果做到最好，浏览 > 编辑  > 巡查管理支持。
1. 可以做，但是会显著增加页面的加载时间而且效果不一定好。这个一般是后台负责处理的，萌百提供了转换功能，但h萌娘上好像是没有。

**Comment by koharubiyori** [comment]
肥肠抱歉，图标换了之后感觉效果不太好；主题在首页取色试了一下，感觉有种偏向うんこ的颜色的感觉...
